### ISSUE TITLE
TestLearningData.createTestLearning fails and prevents deployment

### ISSUE THREAD

**Issue by MarkTranspeed** [forcedotcom/almond#100]
Hi - I've got a problem deploying to Production with a failing test

The routine TestLearningData.createTestLearning fails on line 47: insert lResult;

This is preventing me from deploying my Apex code.

**Comment by jonathanrico** [comment]
hI @MarkTranspeed ,

Have you added any new required fields, custom validation rules or triggers to your Learning__c object? Sounds like there is something preventing the test utility from creating records.

**Comment by MarkTranspeed** [comment]
Hi Jonathan,

No, nothing added.

It looks like a mixed DML issues when I run the test from inside Welkin Suite:

33.0 APEX_CODE,DEBUG;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;NBA,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WAVE,INFO;WORKFLOW,INFO
17:02:56.0 (475663)|USER_INFO|[EXTERNAL]|00524000000lvQA|simon1@transpeed.co.uk|Greenwich Mean Time|GMT+01:00
17:02:56.0 (583977)|EXECUTION_STARTED
17:02:56.0 (607591)|CODE_UNIT_STARTED|[EXTERNAL]|01p1p00000DWeA4|TestTPlanImportAssignmentsExt.testImportWithCustomIndex()
17:02:56.0 (7635136)|SOQL_EXECUTE_BEGIN|[85]|Aggregations:0|SELECT Id, Name, PermissionsCustomizeApplication FROM Profile WHERE Name = :tmpVar1 LIMIT 1
17:02:56.0 (10793809)|SOQL_EXECUTE_END|[85]|Rows:1
17:02:56.0 (13158358)|DML_BEGIN|[106]|Op:Insert|Type:User|Rows:2
17:02:56.0 (302870023)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:02:56.0 (302895135)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:02:56.0 (302993435)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:02:56.0 (303002708)|VALIDATION_PASS
17:02:56.0 (303177389)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:02:56.0 (303366674)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:02:56.0 (303377421)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:02:56.0 (303427925)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:02:56.0 (303435525)|VALIDATION_PASS
17:02:56.0 (303514899)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:02:56.0 (303640578)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:02:56.0 (303650146)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:02:56.0 (303695110)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:02:56.0 (303702996)|VALIDATION_PASS
17:02:56.0 (303776439)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:02:56.0 (303900258)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:02:56.0 (303909689)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:02:56.0 (303953537)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:02:56.0 (303960939)|VALIDATION_PASS
17:02:56.0 (304032351)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:02:56.0 (304156558)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:02:56.0 (304166161)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:02:56.0 (304210207)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:02:56.0 (304217458)|VALIDATION_PASS
17:02:56.0 (304287709)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:02:56.0 (304400044)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:02:56.0 (304409324)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:02:56.0 (304449747)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:02:56.0 (304456436)|VALIDATION_PASS
17:02:56.0 (304525362)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:02:56.414 (414432250)|SOQL_EXECUTE_BEGIN|[586]|Aggregations:0|select Id, AllowedLicenses, UsedLicenses, NamespacePrefix from PackageLicense where NamespacePrefix in :licenseNamespaces and AllowedLicenses >= 1 and Status in ('Active','Trial')
17:02:56.414 (416890096)|SOQL_EXECUTE_END|[586]|Rows:1
17:02:56.414 (417969092)|SOQL_EXECUTE_BEGIN|[267]|Aggregations:0|SELECT Id,UserId,PackageLicense.NamespacePrefix FROM   UserPackageLicense
17:02:56.414 (420754046)|SOQL_EXECUTE_END|[267]|Rows:0
17:02:56.414 (422095124)|DML_BEGIN|[320]|Op:Insert|Type:SObject|Rows:2
17:02:56.414 (452247544)|DML_END|[320]
17:02:56.414 (454821031)|SOQL_EXECUTE_BEGIN|[566]|Aggregations:0|select Id, Name, NamespacePrefix from PermissionSet where Name in :permSetNames and NamespacePrefix in :permSetNamespaces
17:02:56.414 (466884167)|SOQL_EXECUTE_END|[566]|Rows:1
17:02:56.414 (468411937)|SOQL_EXECUTE_BEGIN|[66]|Aggregations:0|SELECT Id,     AssigneeId,     PermissionSetId,     PermissionSet.Name,     PermissionSet.NamespacePrefix FROM       PermissionSetAssignment
17:02:56.414 (471698151)|SOQL_EXECUTE_END|[66]|Rows:0
17:02:56.414 (472724936)|DML_BEGIN|[115]|Op:Insert|Type:SObject|Rows:2
17:02:56.414 (631395975)|DML_END|[115]
17:02:56.632 (632444229)|CUMULATIVE_LIMIT_USAGE
17:02:56.632 (632444229)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 1 out of 100
  Number of query rows: 1 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 1 out of 150
  Number of DML rows: 2 out of 10000
  Maximum CPU time: 63 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:02:56.632 (632444229)|LIMIT_USAGE_FOR_NS|skuid|
  Number of SOQL queries: 4 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 4 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:02:56.632 (632444229)|CUMULATIVE_LIMIT_USAGE_END

17:02:56.0 (658782871)|DML_END|[106]
17:02:56.0 (659426046)|SOQL_EXECUTE_BEGIN|[85]|Aggregations:0|SELECT Id, Name, PermissionsCustomizeApplication FROM Profile WHERE Name = :tmpVar1 LIMIT 1
17:02:56.0 (662194367)|SOQL_EXECUTE_END|[85]|Rows:1
17:02:56.0 (664817898)|DML_BEGIN|[106]|Op:Insert|Type:User|Rows:10
17:02:57.853 (1853563538)|SOQL_EXECUTE_BEGIN|[267]|Aggregations:0|SELECT Id,UserId,PackageLicense.NamespacePrefix FROM   UserPackageLicense
17:02:57.853 (1856889889)|SOQL_EXECUTE_END|[267]|Rows:0
17:02:57.853 (1858661132)|DML_BEGIN|[320]|Op:Insert|Type:SObject|Rows:10
17:02:57.853 (1941689285)|DML_END|[320]
17:02:57.853 (1943173297)|SOQL_EXECUTE_BEGIN|[66]|Aggregations:0|SELECT Id,     AssigneeId,     PermissionSetId,     PermissionSet.Name,     PermissionSet.NamespacePrefix FROM       PermissionSetAssignment
17:02:57.853 (1947806645)|SOQL_EXECUTE_END|[66]|Rows:0
17:02:57.853 (1949412924)|DML_BEGIN|[115]|Op:Insert|Type:SObject|Rows:10
17:02:57.853 (2152075738)|DML_END|[115]
17:02:58.153 (2153051395)|CUMULATIVE_LIMIT_USAGE
17:02:58.153 (2153051395)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 2 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 12 out of 10000
  Maximum CPU time: 187 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:02:58.153 (2153051395)|LIMIT_USAGE_FOR_NS|skuid|
  Number of SOQL queries: 6 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 4 out of 150
  Number of DML rows: 24 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:02:58.153 (2153051395)|CUMULATIVE_LIMIT_USAGE_END

17:02:58.194 (2194745914)|DML_END|[106]
17:02:58.194 (2211713605)|SOQL_EXECUTE_BEGIN|[117]|Aggregations:0|SELECT id FROM PermissionSet WHERE Name = :tmpVar1
17:02:58.194 (2225574331)|SOQL_EXECUTE_END|[117]|Rows:1
17:02:58.194 (2226124037)|DML_BEGIN|[127]|Op:Insert|Type:PermissionSetAssignment|Rows:2
17:02:58.194 (2387317638)|DML_END|[127]
17:02:58.194 (2387832617)|SOQL_EXECUTE_BEGIN|[117]|Aggregations:0|SELECT id FROM PermissionSet WHERE Name = :tmpVar1
17:02:58.194 (2397855432)|SOQL_EXECUTE_END|[117]|Rows:1
17:02:58.194 (2398457967)|DML_BEGIN|[127]|Op:Insert|Type:PermissionSetAssignment|Rows:10
17:02:58.194 (2764048620)|DML_END|[127]
17:02:58.194 (2790995866)|SYSTEM_MODE_ENTER|false
17:02:58.194 (2791037231)|SYSTEM_MODE_EXIT|false
17:02:58.194 (2791099258)|SYSTEM_MODE_ENTER|false
17:02:58.194 (2793777195)|SYSTEM_MODE_EXIT|false
17:02:58.194 (2794060688)|SOQL_EXECUTE_BEGIN|[35]|Aggregations:0|SELECT Id, Name, DeveloperName FROM RecordType WHERE (SobjectType = :tmpVar1 AND DeveloperName = :tmpVar2)
17:02:58.194 (2801136963)|SOQL_EXECUTE_END|[35]|Rows:1
17:02:58.194 (2810901572)|DML_BEGIN|[47]|Op:Insert|Type:Learning__c|Rows:1
17:02:58.194 (2812933706)|DML_END|[47]
17:02:58.194 (2812986903)|EXCEPTION_THROWN|[47]|System.DmlException: Insert failed. First exception on row 0; first error: MIXED_DML_OPERATION, DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): Learning__c, original object: UserPackageLicense: []
17:02:58.194 (2813485548)|FATAL_ERROR|System.DmlException: Insert failed. First exception on row 0; first error: MIXED_DML_OPERATION, DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): Learning__c, original object: UserPackageLicense: []

Class.TestLearningData.createTestLearning: line 47, column 1
Class.TestTrainingPlanData.createSampleData: line 125, column 1
Class.TestTPlanImportAssignmentsExt.testImportWithCustomIndex: line 116, column 1
17:02:58.194 (2813506264)|FATAL_ERROR|System.DmlException: Insert failed. First exception on row 0; first error: MIXED_DML_OPERATION, DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): Learning__c, original object: UserPackageLicense: []

Class.TestLearningData.createTestLearning: line 47, column 1
Class.TestTrainingPlanData.createSampleData: line 125, column 1
Class.TestTPlanImportAssignmentsExt.testImportWithCustomIndex: line 116, column 1
17:02:58.813 (2813608546)|CUMULATIVE_LIMIT_USAGE
17:02:58.813 (2813608546)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 5 out of 100
  Number of query rows: 5 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 6 out of 150
  Number of DML rows: 26 out of 10000
  Maximum CPU time: 380 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:02:58.813 (2813608546)|LIMIT_USAGE_FOR_NS|skuid|
  Number of SOQL queries: 6 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 4 out of 150
  Number of DML rows: 24 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:02:58.813 (2813608546)|CUMULATIVE_LIMIT_USAGE_END

17:02:58.194 (2813662702)|CODE_UNIT_FINISHED|TestTPlanImportAssignmentsExt.testImportWithCustomIndex()
17:02:58.194 (2814534104)|EXECUTION_FINISHED
17:03:02.385 (6385790155)|USER_INFO|[EXTERNAL]|00524000000lvQA|simon1@transpeed.co.uk|Greenwich Mean Time|GMT+01:00
17:03:02.385 (6385820380)|EXECUTION_STARTED
17:03:02.385 (6385826558)|CODE_UNIT_STARTED|[EXTERNAL]|01p1p00000DWeA4|TestTPlanImportAssignmentsExt.testImportWithoutCustomIndex()
17:03:02.385 (6386583958)|SOQL_EXECUTE_BEGIN|[85]|Aggregations:0|SELECT Id, Name, PermissionsCustomizeApplication FROM Profile WHERE Name = :tmpVar1 LIMIT 1
17:03:02.385 (6389898942)|SOQL_EXECUTE_END|[85]|Rows:1
17:03:02.385 (6390817237)|DML_BEGIN|[106]|Op:Insert|Type:User|Rows:2
17:03:02.385 (6639485248)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:03:02.385 (6639509498)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:03:02.385 (6639592077)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:03:02.385 (6639601149)|VALIDATION_PASS
17:03:02.385 (6639720093)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:03:02.385 (6639854512)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:03:02.385 (6639865554)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:03:02.385 (6639911128)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:03:02.385 (6639918063)|VALIDATION_PASS
17:03:02.385 (6639992828)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:03:02.385 (6640110284)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:03:02.385 (6640120981)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:03:02.385 (6640177895)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:03:02.385 (6640188971)|VALIDATION_PASS
17:03:02.385 (6640266710)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:03:02.385 (6640408443)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:03:02.385 (6640418774)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:03:02.385 (6640462764)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:03:02.385 (6640469970)|VALIDATION_PASS
17:03:02.385 (6640543239)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:03:02.385 (6640655520)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:03:02.385 (6640664462)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:03:02.385 (6640706858)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:03:02.385 (6640713315)|VALIDATION_PASS
17:03:02.385 (6640784031)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:03:02.385 (6640901155)|CODE_UNIT_STARTED|[EXTERNAL]|Validation:NetworkMember:new
17:03:02.385 (6640910235)|VALIDATION_RULE|NonNegativeReputationPoints|NonNegativeReputationPoints
17:03:02.385 (6640951332)|VALIDATION_FORMULA|ReputationPoints<0|ReputationPoints=1.0
17:03:02.385 (6640957887)|VALIDATION_PASS
17:03:02.385 (6641028257)|CODE_UNIT_FINISHED|Validation:NetworkMember:new
17:03:02.717 (6717464656)|SOQL_EXECUTE_BEGIN|[586]|Aggregations:0|select Id, AllowedLicenses, UsedLicenses, NamespacePrefix from PackageLicense where NamespacePrefix in :licenseNamespaces and AllowedLicenses >= 1 and Status in ('Active','Trial')
17:03:02.717 (6720014541)|SOQL_EXECUTE_END|[586]|Rows:1
17:03:02.717 (6720762408)|SOQL_EXECUTE_BEGIN|[267]|Aggregations:0|SELECT Id,UserId,PackageLicense.NamespacePrefix FROM   UserPackageLicense
17:03:02.717 (6723698610)|SOQL_EXECUTE_END|[267]|Rows:0
17:03:02.717 (6724516554)|DML_BEGIN|[320]|Op:Insert|Type:SObject|Rows:2
17:03:02.717 (6761830883)|DML_END|[320]
17:03:02.717 (6763365740)|SOQL_EXECUTE_BEGIN|[566]|Aggregations:0|select Id, Name, NamespacePrefix from PermissionSet where Name in :permSetNames and NamespacePrefix in :permSetNamespaces
17:03:02.717 (6778198998)|SOQL_EXECUTE_END|[566]|Rows:1
17:03:02.717 (6779177093)|SOQL_EXECUTE_BEGIN|[66]|Aggregations:0|SELECT Id,     AssigneeId,     PermissionSetId,     PermissionSet.Name,     PermissionSet.NamespacePrefix FROM       PermissionSetAssignment
17:03:02.717 (6782723980)|SOQL_EXECUTE_END|[66]|Rows:0
17:03:02.717 (6783795156)|DML_BEGIN|[115]|Op:Insert|Type:SObject|Rows:2
17:03:02.717 (6899586549)|DML_END|[115]
17:03:02.900 (6900630712)|CUMULATIVE_LIMIT_USAGE
17:03:02.900 (6900630712)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 1 out of 100
  Number of query rows: 1 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 1 out of 150
  Number of DML rows: 2 out of 10000
  Maximum CPU time: 40 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:03:02.900 (6900630712)|LIMIT_USAGE_FOR_NS|skuid|
  Number of SOQL queries: 4 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 4 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:03:02.900 (6900630712)|CUMULATIVE_LIMIT_USAGE_END

17:03:02.385 (6924472921)|DML_END|[106]
17:03:02.385 (6925131049)|SOQL_EXECUTE_BEGIN|[85]|Aggregations:0|SELECT Id, Name, PermissionsCustomizeApplication FROM Profile WHERE Name = :tmpVar1 LIMIT 1
17:03:02.385 (6929206779)|SOQL_EXECUTE_END|[85]|Rows:1
17:03:02.385 (6931974321)|DML_BEGIN|[106]|Op:Insert|Type:User|Rows:10
17:03:04.143 (8143297672)|SOQL_EXECUTE_BEGIN|[267]|Aggregations:0|SELECT Id,UserId,PackageLicense.NamespacePrefix FROM   UserPackageLicense
17:03:04.143 (8147052109)|SOQL_EXECUTE_END|[267]|Rows:0
17:03:04.143 (8148613404)|DML_BEGIN|[320]|Op:Insert|Type:SObject|Rows:10
17:03:04.143 (8233074212)|DML_END|[320]
17:03:04.143 (8234474654)|SOQL_EXECUTE_BEGIN|[66]|Aggregations:0|SELECT Id,     AssigneeId,     PermissionSetId,     PermissionSet.Name,     PermissionSet.NamespacePrefix FROM       PermissionSetAssignment
17:03:04.143 (8240171635)|SOQL_EXECUTE_END|[66]|Rows:0
17:03:04.143 (8241626927)|DML_BEGIN|[115]|Op:Insert|Type:SObject|Rows:10
17:03:04.143 (8486367296)|DML_END|[115]
17:03:04.487 (8487322910)|CUMULATIVE_LIMIT_USAGE
17:03:04.487 (8487322910)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 2 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 12 out of 10000
  Maximum CPU time: 125 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:03:04.487 (8487322910)|LIMIT_USAGE_FOR_NS|skuid|
  Number of SOQL queries: 6 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 4 out of 150
  Number of DML rows: 24 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:03:04.487 (8487322910)|CUMULATIVE_LIMIT_USAGE_END

17:03:04.526 (8526473171)|DML_END|[106]
17:03:04.526 (8543211739)|SOQL_EXECUTE_BEGIN|[117]|Aggregations:0|SELECT id FROM PermissionSet WHERE Name = :tmpVar1
17:03:04.526 (8555518949)|SOQL_EXECUTE_END|[117]|Rows:1
17:03:04.526 (8556074374)|DML_BEGIN|[127]|Op:Insert|Type:PermissionSetAssignment|Rows:2
17:03:04.526 (8650376961)|DML_END|[127]
17:03:04.526 (8650647803)|SOQL_EXECUTE_BEGIN|[117]|Aggregations:0|SELECT id FROM PermissionSet WHERE Name = :tmpVar1
17:03:04.526 (8662072335)|SOQL_EXECUTE_END|[117]|Rows:1
17:03:04.526 (8662706716)|DML_BEGIN|[127]|Op:Insert|Type:PermissionSetAssignment|Rows:10
17:03:04.526 (9236755981)|DML_END|[127]
17:03:04.526 (9247986263)|SYSTEM_MODE_ENTER|false
17:03:04.526 (9248021597)|SYSTEM_MODE_EXIT|false
17:03:04.526 (9248055953)|SYSTEM_MODE_ENTER|false
17:03:04.526 (9248221866)|SYSTEM_MODE_EXIT|false
17:03:04.526 (9248598964)|SOQL_EXECUTE_BEGIN|[35]|Aggregations:0|SELECT Id, Name, DeveloperName FROM RecordType WHERE (SobjectType = :tmpVar1 AND DeveloperName = :tmpVar2)
17:03:04.526 (9253021161)|SOQL_EXECUTE_END|[35]|Rows:1
17:03:04.526 (9253644344)|DML_BEGIN|[47]|Op:Insert|Type:Learning__c|Rows:1
17:03:04.526 (9255583510)|DML_END|[47]
17:03:04.526 (9255635709)|EXCEPTION_THROWN|[47]|System.DmlException: Insert failed. First exception on row 0; first error: MIXED_DML_OPERATION, DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): Learning__c, original object: UserPackageLicense: []
17:03:04.526 (9256145073)|FATAL_ERROR|System.DmlException: Insert failed. First exception on row 0; first error: MIXED_DML_OPERATION, DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): Learning__c, original object: UserPackageLicense: []

Class.TestLearningData.createTestLearning: line 47, column 1
Class.TestTrainingPlanData.createSampleData: line 125, column 1
Class.TestTPlanImportAssignmentsExt.testImportWithoutCustomIndex: line 45, column 1
17:03:04.526 (9256168021)|FATAL_ERROR|System.DmlException: Insert failed. First exception on row 0; first error: MIXED_DML_OPERATION, DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): Learning__c, original object: UserPackageLicense: []

Class.TestLearningData.createTestLearning: line 47, column 1
Class.TestTrainingPlanData.createSampleData: line 125, column 1
Class.TestTPlanImportAssignmentsExt.testImportWithoutCustomIndex: line 45, column 1
17:03:05.256 (9256189684)|CUMULATIVE_LIMIT_USAGE
17:03:05.256 (9256189684)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 5 out of 100
  Number of query rows: 5 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 6 out of 150
  Number of DML rows: 26 out of 10000
  Maximum CPU time: 282 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:03:05.256 (9256189684)|LIMIT_USAGE_FOR_NS|skuid|
  Number of SOQL queries: 6 out of 100
  Number of query rows: 2 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 4 out of 150
  Number of DML rows: 24 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

17:03:05.256 (9256189684)|CUMULATIVE_LIMIT_USAGE_END

17:03:04.526 (9256239935)|CODE_UNIT_FINISHED|TestTPlanImportAssignmentsExt.testImportWithoutCustomIndex()
17:03:04.526 (9257476831)|EXECUTION_FINISHED


Cheers,

Mark

**Comment by jonathanrico** [comment]
I see a reference to UserPackageLicense . Do you have any trigger, flow or workflow trying to insert this object. The package doesn't have any references to this object out of the box.

**Comment by MarkTranspeed** [comment]
Jo Jonathan,

No, not that I can see

Cheers,

Mark

**Comment by jonathanrico** [comment]
Closing this issue for now, I was not able to replicate and the affected object is not part of the almond package.
