### ISSUE TITLE
BUG in the Almond - Learning Management application

### ISSUE THREAD

**Issue by IsabelleFernandes** [forcedotcom/almond#101]
Hi, @jonathanrico 

When the user executes a task from a course in the Almond - Learning Management application, he clicks on the "Execute" button and reads the information.
To proceed the user can:

1 - Click the button "Done!" to proceed with the course;
2 - Click the button "Still working on it" to proceed and not mark the task as it was concluded;
3 - Click the arrow / button to return to the previous screen.

In case 3, when this is done on the iPad, the system is processing, processing and does not return to the previous screen, or rather does not finish processing.

See attached file.

**Comment by IsabelleFernandes** [comment]
[Issue_101.pdf](https://github.com/forcedotcom/almond/files/2210297/Issue_101.pdf)

**Comment by jonathanrico** [comment]
@IsabelleFernandes , is this only happening on an ipad? if so what browser are you using?

**Comment by IsabelleFernandes** [comment]
Good morning @jonathanrico! Do you have any answers for us?

**Comment by IsabelleFernandes** [comment]
Good morning @jonathanrico! Do you have any answers for us?

**Comment by jonathanrico** [comment]
Hey Isabelle, no updates yet. Will probably be able to take a look it sometime next week.

**Comment by IsabelleFernandes** [comment]
@jonathanrico, thank you very much for the answer.

**Comment by IsabelleFernandes** [comment]
Hello @jonathanrico! Do you have any answers for us?

**Comment by IsabelleFernandes** [comment]
Hello @jonathanrico! Do you have any answers for us?
