### ISSUE TITLE
Support communities

### ISSUE THREAD

**Issue by jonathanrico** [forcedotcom/almond#38]
Allow admins to assign training plans to users that have community licenses and expose almond vf pages inside communities.

**Comment by akshay-kathpal-grazitti** [comment]
Hi, I have also a scenario where I have exposed the almond-lms via iframe in Communities. Everything is working fine but I am getting error in Launching the quiz, but for task and learning resource it is working fine. Here are the screenshots. I have LMS running on production URL and Sandbox URL. The quiz pages are showing in Sandbox but not in Production. Here are the screenshots for more information.

1. Working correctly in Community

![1-front-comm](https://user-images.githubusercontent.com/54700194/68290814-9d349580-00ae-11ea-92f4-a49acb29b1a5.png)

2. Resource is opening.

![2-working-for-resource-learning](https://user-images.githubusercontent.com/54700194/68290869-b3425600-00ae-11ea-8c02-4ef5f85371d1.png)

3. Task is also opening 

![2-working-for-task-learning](https://user-images.githubusercontent.com/54700194/68290914-c9e8ad00-00ae-11ea-8355-c601888e3308.png)


4. But not for Quiz

![2-not-working-for-quiz](https://user-images.githubusercontent.com/54700194/68290941-d240e800-00ae-11ea-80d2-b5d10aa3653c.png)


In debugging I have found some error which can help to resolve this issue.

my production URL : https://akshay-grazitti-developer-edition.ap15.force.com/apex/trainingplandetail?id=a0y2v00000AUSMQAA5

![4-production](https://user-images.githubusercontent.com/54700194/68291078-1633ed00-00af-11ea-9f39-fd80680dec77.png)

on clicking launch It redirects us to https://apex/QuizResults?aid=a0a2v00000aNA2EAAW 
instead it should redirect to https://akshay-grazitti-developer-edition.ap15.force.com/apex/QuizResults?aid=a0a2v00000aNA2EAAW 

which yields the proper result.

But for sandbox it is working fine.
