### ISSUE TITLE
Quiz error: You must answer all of the questions to continue (IE 9)

### ISSUE THREAD

**Issue by ricex242** [forcedotcom/almond#81]
Our users accessing quizzes on Internet Explorer 9 encounter the error **_You must answer all of the questions to continue_** when attempting to submit a quiz. They receive this error even after multiple attempts answering all questions, with all the correct answers. This is not an issue in Chrome. 

Has anyone else encountered this and found a workaround? @jonathanrico ?

And yes, I know, IE is the bane of web existence. These are corporate folks who don't have install rights on their work PCs, though, so switching them to Chrome isn't a fix in this case.

**Comment by jonathanrico** [comment]
Thanks for reporting this, i'll take a look as soon as I can get my hands on a PC with IE9.
