### ISSUE TITLE
Training Track - launch button

### ISSUE THREAD

**Issue by gretacooke01** [forcedotcom/almond#97]
Hello,
 
I am having a problem setting up a training track. My test participants aren't seeing the "Launch" button of some of the learnings. I can see them if I go to my own training, but I can't figure out why other people can't see them. I think I have tried updating everything but I keep getting stuck.
 
I attached a screenshot of my test participant's screen.
 
Can someone help me? 

![almond-launch problem](https://cloud.githubusercontent.com/assets/24722396/21437677/3cd2d936-c853-11e6-94f5-210d5e4ffbcc.png)

**Comment by jonathanrico** [comment]
Hi @gretacooke01 ,

To solve this, go to your training plan and click the "Manage Assignments" button. Then go to the "Batch Operations" tab and click the "Update all assignments" button. You have to do this everytime you add new learning objects to a training plan that has already been assigned to users.

Also, this should be documented in the user guide. You can find it in the Appexchange listing under the "Details" tab.
