### ISSUE TITLE
Invalid Assignment Id

### ISSUE THREAD

**Issue by hsmedrado** [forcedotcom/almond#99]
[apex-07L0a00001XoQo7EAF.log](https://github.com/forcedotcom/almond/files/1412447/apex-07L0a00001XoQo7EAF.log)
Almond was working properly. After Winter 18 we start to receive the error "Invalid Assignment Id" as soon as I open a Learning. 
Attached the log.

**Comment by jonathanrico** [comment]
@hsmedrado I was not able to reproduce this issue and unfortunately I can't see this exception in the logs you provided. will close this issue for now as this seems to be related to a specific implementation of almond in your org.
